language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN