language: node_js
node_js:
- node
warnings_are_errors: false
before_install:
- bash script/deploy.sh
install:
- npm install
- npm install -g firebase-tools
script:
- npm run build
after_success:
- firebase deploy --token $FIREBASE_TOKEN